import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { ExternalLink, Inbox, LayoutDashboard, LogOut, Plus, Save, Trash2 } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import type { Json, Tables } from "@/integrations/supabase/types";

type Project=Tables<"projects">; type Skill=Tables<"skills">; type Experience=Tables<"experiences">; type Message=Tables<"contact_messages">; type Category=Tables<"project_categories">;
type ContentValue=Record<string,string|string[]>;

export const Route=createFileRoute("/_authenticated/dashboard")({head:()=>({meta:[{title:"Dashboard — Bouissa Mohamed"},{name:"description",content:"Manage all portfolio content and enquiries."},{property:"og:title",content:"Portfolio Dashboard"},{property:"og:description",content:"Manage all portfolio content and enquiries."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Dashboard});

function Dashboard(){
  const navigate=useNavigate(); const queryClient=useQueryClient();
  const [projects,setProjects]=useState<Project[]>([]); const[skills,setSkills]=useState<Skill[]>([]); const[experiences,setExperiences]=useState<Experience[]>([]); const[messages,setMessages]=useState<Message[]>([]); const[categories,setCategories]=useState<Category[]>([]);
  const[profile,setProfile]=useState<ContentValue>({}); const[about,setAbout]=useState<ContentValue>({}); const[contact,setContact]=useState<ContentValue>({}); const[status,setStatus]=useState("");

  async function load(){
    const [p,s,e,m,c,pc]=await Promise.all([
      supabase.from("projects").select("*").order("sort_order"), supabase.from("skills").select("*").order("sort_order"),
      supabase.from("experiences").select("*").order("sort_order"), supabase.from("contact_messages").select("*").order("created_at",{ascending:false}),
      supabase.from("site_content").select("key,value"), supabase.from("project_categories").select("*").order("sort_order"),
    ]);
    setProjects(p.data??[]); setSkills(s.data??[]); setExperiences(e.data??[]); setMessages(m.data??[]); setCategories(pc.data??[]);
    for(const row of c.data??[]){if(row.key==="profile")setProfile(row.value as ContentValue);if(row.key==="about")setAbout(row.value as ContentValue);if(row.key==="contact")setContact(row.value as ContentValue);}
  }
  useEffect(()=>{void load()},[]);
  const saved=()=>{setStatus("Saved");setTimeout(()=>setStatus(""),1800)};
  async function saveContent(key:string,value:ContentValue){const {error}=await supabase.from("site_content").update({value:value as Json,updated_at:new Date().toISOString()}).eq("key",key);if(!error)saved();}
  async function saveProject(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const id=String(f.get("id"));const payload={title:String(f.get("title")),description:String(f.get("description")),category_slug:String(f.get("category_slug")),image_url:String(f.get("image_url")),demo_url:String(f.get("demo_url")),code_url:String(f.get("code_url")),technologies:String(f.get("technologies")).split(",").map(x=>x.trim()).filter(Boolean),featured:f.get("featured")==="on",published:f.get("published")==="on",sort_order:Number(f.get("sort_order"))};if(id)await supabase.from("projects").update(payload).eq("id",id);else await supabase.from("projects").insert(payload);await load();saved();}
  async function remove(table:"projects"|"skills"|"experiences"|"project_categories",id:string,label:string){if(!confirm(`Delete ${label}?`))return;await supabase.from(table).delete().eq("id",id);await load();saved();}
  async function saveSkill(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const id=String(f.get("id"));const payload={name:String(f.get("name")),group_name:String(f.get("group_name")||"Engineering"),level:Number(f.get("level")||80),sort_order:Number(f.get("sort_order")),published:f.get("published")==="on"};if(id)await supabase.from("skills").update(payload).eq("id",id);else await supabase.from("skills").insert(payload);await load();saved();}
  async function saveExperience(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const id=String(f.get("id"));const payload={period:String(f.get("period")),role_title:String(f.get("role_title")),company:String(f.get("company")),level:Number(f.get("level")||1),sort_order:Number(f.get("sort_order")),published:f.get("published")==="on"};if(id)await supabase.from("experiences").update(payload).eq("id",id);else await supabase.from("experiences").insert(payload);await load();saved();}
  async function saveCategory(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const id=String(f.get("id"));const payload={name:String(f.get("name")),slug:String(f.get("slug")),sort_order:Number(f.get("sort_order")),published:f.get("published")==="on"};if(id)await supabase.from("project_categories").update(payload).eq("id",id);else await supabase.from("project_categories").insert(payload);await load();saved();}
  async function signOut(){await queryClient.cancelQueries();queryClient.clear();await supabase.auth.signOut();await navigate({to:"/admin",replace:true});}

  return <main className="min-h-screen bg-background"><header className="sticky top-0 z-20 border-b border-border bg-background/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1500px] items-center justify-between px-5"><div className="flex items-center gap-3"><LayoutDashboard className="text-primary"/><strong className="font-display uppercase">Portfolio OS</strong>{status&&<span className="text-xs text-primary">{status}</span>}</div><div className="flex gap-2"><Button variant="outline" size="sm" asChild><a href="/" target="_blank">View site <ExternalLink/></a></Button><Button variant="ghost" size="icon" onClick={signOut} aria-label="Sign out"><LogOut/></Button></div></div></header><div className="mx-auto max-w-[1500px] p-5 lg:p-8"><div className="mb-8"><p className="eyebrow">Private workspace</p><h1 className="mt-2 font-display text-4xl font-bold uppercase">Content dashboard</h1></div><Tabs defaultValue="identity"><TabsList className="h-auto w-full justify-start overflow-x-auto bg-surface p-1"><TabsTrigger value="identity">Identity</TabsTrigger><TabsTrigger value="projects">Projects</TabsTrigger><TabsTrigger value="categories">Categories</TabsTrigger><TabsTrigger value="skills">Skills</TabsTrigger><TabsTrigger value="experience">Experience</TabsTrigger><TabsTrigger value="messages">Messages ({messages.filter(m=>m.status==="new").length})</TabsTrigger></TabsList>
    <TabsContent value="identity" className="mt-6 grid gap-6 lg:grid-cols-3"><ContentEditor title="Profile & hero" value={profile} fields={["name","role","tagline","portrait","since","years"]} onSave={v=>{setProfile(v);void saveContent("profile",v)}}/><ContentEditor title="About" value={about} fields={["heading","body","focus"]} arrayFields={["focus"]} onSave={v=>{setAbout(v);void saveContent("about",v)}}/><ContentEditor title="Contact" value={contact} fields={["email","whatsapp","linkedin","github","availability"]} onSave={v=>{setContact(v);void saveContent("contact",v)}}/></TabsContent>
    <TabsContent value="projects" className="mt-6"><details className="mb-6 border border-primary/50 bg-primary/5 p-5"><summary className="cursor-pointer font-display font-bold uppercase"><Plus className="mr-2 inline size-4"/>Add project</summary><ProjectForm categories={categories} onSubmit={saveProject}/></details><div className="grid gap-4 lg:grid-cols-2">{projects.map(p=><details key={p.id} className="border border-border bg-surface p-5"><summary className="cursor-pointer font-semibold">{p.title} <span className="ml-2 text-xs text-muted-foreground">{p.published?"Published":"Draft"}</span></summary><ProjectForm project={p} categories={categories} onSubmit={saveProject} onDelete={()=>remove("projects",p.id,p.title)}/></details>)}</div></TabsContent>
    <TabsContent value="categories" className="mt-6"><CreatePanel label="Add category"><CategoryForm onSubmit={saveCategory}/></CreatePanel><div className="space-y-3">{categories.map(row=><CategoryForm key={row.id} category={row} onSubmit={saveCategory} onDelete={()=>remove("project_categories",row.id,row.name)}/>)}</div></TabsContent>
    <TabsContent value="skills" className="mt-6"><CreatePanel label="Add skill"><SkillForm onSubmit={saveSkill}/></CreatePanel><div className="grid gap-3 lg:grid-cols-2">{skills.map(row=><SkillForm key={row.id} skill={row} onSubmit={saveSkill} onDelete={()=>remove("skills",row.id,row.name)}/>)}</div></TabsContent>
    <TabsContent value="experience" className="mt-6"><CreatePanel label="Add experience"><ExperienceForm onSubmit={saveExperience}/></CreatePanel><div className="space-y-3">{experiences.map(row=><ExperienceForm key={row.id} experience={row} onSubmit={saveExperience} onDelete={()=>remove("experiences",row.id,row.role_title)}/>)}</div></TabsContent>
    <TabsContent value="messages" className="mt-6 space-y-3">{messages.length===0?<p className="border border-dashed border-border p-12 text-center text-muted-foreground"><Inbox className="mx-auto mb-3"/>No messages yet.</p>:messages.map(m=><article key={m.id} className="border border-border bg-surface p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">{m.subject}</h3><a href={`mailto:${m.email}`} className="text-sm text-primary">{m.name} · {m.email}</a></div><span className="font-mono text-xs text-muted-foreground">{new Date(m.created_at).toLocaleString()}</span></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{m.message}</p><div className="mt-4 flex gap-2"><Button size="sm" variant="outline" onClick={async()=>{await supabase.from("contact_messages").update({status:m.status==="read"?"new":"read"}).eq("id",m.id);await load()}}>{m.status==="read"?"Mark unread":"Mark read"}</Button><Button size="icon" variant="destructive" aria-label="Delete message" onClick={async()=>{if(confirm("Delete this message?")){await supabase.from("contact_messages").delete().eq("id",m.id);await load()}}}><Trash2/></Button></div></article>)}</TabsContent>
  </Tabs></div></main>;
}

function ContentEditor({title,value,fields,arrayFields=[],onSave}:{title:string;value:ContentValue;fields:string[];arrayFields?:string[];onSave:(v:ContentValue)=>void}){const[local,setLocal]=useState(value);useEffect(()=>setLocal(value),[value]);return <section className="border border-border bg-surface p-5"><h2 className="mb-5 font-display text-xl font-bold uppercase">{title}</h2><div className="space-y-4">{fields.map(field=>{const raw=local[field];const shown=Array.isArray(raw)?raw.join("\n"):raw??"";const multiline=field==="body"||field==="tagline"||field==="availability"||arrayFields.includes(field);return <label key={field} className="field-label capitalize">{field}{multiline?<Textarea value={shown} onChange={e=>setLocal({...local,[field]:arrayFields.includes(field)?e.target.value.split("\n").map(x=>x.trim()).filter(Boolean):e.target.value})}/>:<Input value={shown} onChange={e=>setLocal({...local,[field]:e.target.value})}/>}</label>})}<Button onClick={()=>onSave(local)}><Save/>Save</Button></div></section>}
function CreatePanel({label,children}:{label:string;children:React.ReactNode}){return <details className="mb-6 border border-primary/50 bg-primary/5 p-5"><summary className="cursor-pointer font-display font-bold uppercase"><Plus className="mr-2 inline size-4"/>{label}</summary>{children}</details>}
function CheckField({name,label,checked=true}:{name:string;label:string;checked?:boolean}){return <label className="flex items-center gap-2 text-sm"><input name={name} type="checkbox" defaultChecked={checked}/>{label}</label>}
function ProjectForm({project,categories,onSubmit,onDelete}:{project?:Project;categories:Category[];onSubmit:(e:FormEvent<HTMLFormElement>)=>void;onDelete?:()=>void}){return <form onSubmit={onSubmit} className="mt-5 grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value={project?.id??""}/><Input name="title" placeholder="Project title" defaultValue={project?.title} required/><select name="category_slug" defaultValue={project?.category_slug??categories[0]?.slug??"web"} className="h-9 border border-input bg-background px-3 text-sm" required>{categories.map(c=><option key={c.id} value={c.slug}>{c.name}</option>)}</select><Textarea className="sm:col-span-2" name="description" placeholder="Description" defaultValue={project?.description} required/><Input name="image_url" placeholder="Image URL" defaultValue={project?.image_url}/><Input name="demo_url" placeholder="Live project URL" defaultValue={project?.demo_url}/><Input name="code_url" placeholder="Code URL" defaultValue={project?.code_url}/><Input name="sort_order" type="number" placeholder="Order" defaultValue={project?.sort_order??99}/><Input className="sm:col-span-2" name="technologies" placeholder="Technologies, comma separated" defaultValue={project?.technologies.join(", ")}/><CheckField name="featured" label="Featured" checked={project?.featured??false}/><CheckField name="published" label="Published" checked={project?.published??true}/><div className="flex gap-2 sm:col-span-2"><Button type="submit"><Save/>Save project</Button>{onDelete&&<Button type="button" variant="destructive" onClick={onDelete}><Trash2/>Delete</Button>}</div></form>}
function SkillForm({skill,onSubmit,onDelete}:{skill?:Skill;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;onDelete?:()=>void}){return <form onSubmit={onSubmit} className="grid gap-3 border border-border bg-surface p-4 sm:grid-cols-2 lg:grid-cols-5"><input type="hidden" name="id" value={skill?.id??""}/><Input name="name" placeholder="Skill" defaultValue={skill?.name} required/><Input name="group_name" placeholder="Internal group" defaultValue={skill?.group_name??"Engineering"}/><Input name="level" type="hidden" value={skill?.level??80}/><Input name="sort_order" type="number" placeholder="Order" defaultValue={skill?.sort_order??99}/><CheckField name="published" label="Published" checked={skill?.published??true}/><div className="flex gap-2"><Button type="submit" size="icon" aria-label="Save skill"><Save/></Button>{onDelete&&<Button type="button" size="icon" variant="destructive" aria-label="Delete skill" onClick={onDelete}><Trash2/></Button>}</div></form>}
function ExperienceForm({experience,onSubmit,onDelete}:{experience?:Experience;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;onDelete?:()=>void}){return <form onSubmit={onSubmit} className="grid gap-3 border border-border bg-surface p-4 md:grid-cols-6"><input type="hidden" name="id" value={experience?.id??""}/><Input name="period" placeholder="Period" defaultValue={experience?.period} required/><Input name="role_title" placeholder="Role title" defaultValue={experience?.role_title} required/><Input name="company" placeholder="Company" defaultValue={experience?.company} required/><Input name="level" type="number" placeholder="Number" defaultValue={experience?.level??1}/><Input name="sort_order" type="number" placeholder="Order" defaultValue={experience?.sort_order??99}/><div className="flex items-center gap-2"><CheckField name="published" label="Published" checked={experience?.published??true}/><Button type="submit" size="icon" aria-label="Save experience"><Save/></Button>{onDelete&&<Button type="button" size="icon" variant="destructive" aria-label="Delete experience" onClick={onDelete}><Trash2/></Button>}</div></form>}
function CategoryForm({category,onSubmit,onDelete}:{category?:Category;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;onDelete?:()=>void}){return <form onSubmit={onSubmit} className="mt-3 grid gap-3 border border-border bg-surface p-4 sm:grid-cols-5"><input type="hidden" name="id" value={category?.id??""}/><Input name="name" placeholder="Category name" defaultValue={category?.name} required/><Input name="slug" placeholder="category-slug" defaultValue={category?.slug} required/><Input name="sort_order" type="number" placeholder="Order" defaultValue={category?.sort_order??99}/><CheckField name="published" label="Published" checked={category?.published??true}/><div className="flex gap-2"><Button type="submit" size="icon" aria-label="Save category"><Save/></Button>{onDelete&&<Button type="button" size="icon" variant="destructive" aria-label="Delete category" onClick={onDelete}><Trash2/></Button>}</div></form>}