import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { ExternalLink, Inbox, LayoutDashboard, LogOut, Plus, Save, Trash2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import type { Tables } from "@/integrations/supabase/types";

type Project=Tables<"projects">;type Skill=Tables<"skills">;type Experience=Tables<"experiences">;type Message=Tables<"contact_messages">;
export const Route=createFileRoute("/_authenticated/dashboard")({head:()=>({meta:[{title:"Dashboard — Bouissa Mohamed"},{name:"description",content:"Manage portfolio content and enquiries."},{property:"og:title",content:"Portfolio Dashboard"},{property:"og:description",content:"Manage portfolio content and enquiries."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Dashboard});

function Dashboard(){const navigate=useNavigate();const [projects,setProjects]=useState<Project[]>([]);const[skills,setSkills]=useState<Skill[]>([]);const[experiences,setExperiences]=useState<Experience[]>([]);const[messages,setMessages]=useState<Message[]>([]);const[profile,setProfile]=useState<Record<string,string>>({});const[about,setAbout]=useState<Record<string,string>>({});const[contact,setContact]=useState<Record<string,string>>({});const[status,setStatus]=useState("");
  async function load(){const [p,s,e,m,c]=await Promise.all([supabase.from("projects").select("*").order("sort_order"),supabase.from("skills").select("*").order("sort_order"),supabase.from("experiences").select("*").order("sort_order"),supabase.from("contact_messages").select("*").order("created_at",{ascending:false}),supabase.from("site_content").select("key,value")]);setProjects(p.data??[]);setSkills(s.data??[]);setExperiences(e.data??[]);setMessages(m.data??[]);for(const row of c.data??[]){if(row.key==="profile")setProfile(row.value as Record<string,string>);if(row.key==="about")setAbout(row.value as Record<string,string>);if(row.key==="contact")setContact(row.value as Record<string,string>);}}
  useEffect(()=>{void load()},[]); const saved=()=>{setStatus("Saved");setTimeout(()=>setStatus(""),1800)};
  async function saveContent(key:string,value:Record<string,string>){const {error}=await supabase.from("site_content").update({value,updated_at:new Date().toISOString()}).eq("key",key);if(!error)saved();}
  async function saveProject(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const id=String(f.get("id"));const payload={title:String(f.get("title")),description:String(f.get("description")),category_slug:String(f.get("category_slug")),image_url:String(f.get("image_url")),demo_url:String(f.get("demo_url")),technologies:String(f.get("technologies")).split(",").map(x=>x.trim()).filter(Boolean),published:f.get("published")==="on",sort_order:Number(f.get("sort_order"))};if(id)await supabase.from("projects").update(payload).eq("id",id);else await supabase.from("projects").insert(payload);await load();saved();}
  async function removeProject(id:string){if(!confirm("Delete this project?"))return;await supabase.from("projects").delete().eq("id",id);await load();}
  async function signOut(){await supabase.auth.signOut();await navigate({to:"/auth",replace:true});}
  return <main className="min-h-screen bg-background"><header className="sticky top-0 z-20 border-b border-border bg-background/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1500px] items-center justify-between px-5"><div className="flex items-center gap-3"><LayoutDashboard className="text-primary"/><strong className="font-display uppercase">Portfolio OS</strong>{status&&<span className="text-xs text-primary">{status}</span>}</div><div className="flex gap-2"><Button variant="outline" size="sm" asChild><a href="/" target="_blank">View site <ExternalLink/></a></Button><Button variant="ghost" size="icon" onClick={signOut} aria-label="Sign out"><LogOut/></Button></div></div></header><div className="mx-auto max-w-[1500px] p-5 lg:p-8"><div className="mb-8"><p className="eyebrow">Private workspace</p><h1 className="mt-2 font-display text-4xl font-bold uppercase">Content dashboard</h1></div><Tabs defaultValue="identity"><TabsList className="h-auto w-full justify-start overflow-x-auto bg-surface p-1"><TabsTrigger value="identity">Identity</TabsTrigger><TabsTrigger value="projects">Projects</TabsTrigger><TabsTrigger value="skills">Skills</TabsTrigger><TabsTrigger value="experience">Experience</TabsTrigger><TabsTrigger value="messages">Messages ({messages.filter(m=>m.status==="new").length})</TabsTrigger></TabsList>
    <TabsContent value="identity" className="mt-6 grid gap-6 lg:grid-cols-3"><ContentEditor title="Profile & hero" value={profile} fields={["name","role","tagline","portrait","since","years"]} onSave={v=>{setProfile(v);void saveContent("profile",v)}}/><ContentEditor title="About" value={about} fields={["heading","body"]} onSave={v=>{setAbout(v);void saveContent("about",v)}}/><ContentEditor title="Contact" value={contact} fields={["email","whatsapp","linkedin","availability"]} onSave={v=>{setContact(v);void saveContent("contact",v)}}/></TabsContent>
    <TabsContent value="projects" className="mt-6"><details className="mb-6 border border-primary/50 bg-primary/5 p-5"><summary className="cursor-pointer font-display font-bold uppercase"><Plus className="mr-2 inline size-4"/>Add project</summary><ProjectForm onSubmit={saveProject}/></details><div className="grid gap-4 lg:grid-cols-2">{projects.map(p=><details key={p.id} className="border border-border bg-surface p-5"><summary className="cursor-pointer font-semibold">{p.title} <span className="ml-2 text-xs text-muted-foreground">{p.published?"Published":"Draft"}</span></summary><ProjectForm project={p} onSubmit={saveProject} onDelete={()=>removeProject(p.id)}/></details>)}</div></TabsContent>
    <TabsContent value="skills" className="mt-6"><SimpleTable rows={skills} columns={["name","group_name","level","sort_order"]} table="skills" reload={load}/></TabsContent>
    <TabsContent value="experience" className="mt-6"><SimpleTable rows={experiences} columns={["period","role_title","company","level","sort_order"]} table="experiences" reload={load}/></TabsContent>
    <TabsContent value="messages" className="mt-6 space-y-3">{messages.length===0?<p className="border border-dashed border-border p-12 text-center text-muted-foreground"><Inbox className="mx-auto mb-3"/>No messages yet.</p>:messages.map(m=><article key={m.id} className="border border-border bg-surface p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">{m.subject}</h3><a href={`mailto:${m.email}`} className="text-sm text-primary">{m.name} · {m.email}</a></div><span className="font-mono text-xs text-muted-foreground">{new Date(m.created_at).toLocaleString()}</span></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{m.message}</p><Button className="mt-4" size="sm" variant="outline" onClick={async()=>{await supabase.from("contact_messages").update({status:"read"}).eq("id",m.id);await load()}}>Mark read</Button></article>)}</TabsContent>
  </Tabs></div></main>}

function ContentEditor({title,value,fields,onSave}:{title:string;value:Record<string,string>;fields:string[];onSave:(v:Record<string,string>)=>void}){const[local,setLocal]=useState(value);useEffect(()=>setLocal(value),[value]);return <section className="border border-border bg-surface p-5"><h2 className="mb-5 font-display text-xl font-bold uppercase">{title}</h2><div className="space-y-4">{fields.map(field=><label key={field} className="field-label capitalize">{field}{field==="body"||field==="tagline"||field==="availability"?<Textarea value={local[field]??""} onChange={e=>setLocal({...local,[field]:e.target.value})}/>:<Input value={local[field]??""} onChange={e=>setLocal({...local,[field]:e.target.value})}/>}</label>)}<Button onClick={()=>onSave(local)}><Save/>Save</Button></div></section>}
function ProjectForm({project,onSubmit,onDelete}:{project?:Project;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;onDelete?:()=>void}){return <form onSubmit={onSubmit} className="mt-5 grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value={project?.id??""}/><Input name="title" placeholder="Project title" defaultValue={project?.title} required/><Input name="category_slug" placeholder="Category slug" defaultValue={project?.category_slug??"web"} required/><Textarea className="sm:col-span-2" name="description" placeholder="Description" defaultValue={project?.description} required/><Input name="image_url" placeholder="Image URL" defaultValue={project?.image_url}/><Input name="demo_url" placeholder="Demo URL" defaultValue={project?.demo_url}/><Input className="sm:col-span-2" name="technologies" placeholder="Technologies, comma separated" defaultValue={project?.technologies.join(", ")}/><Input name="sort_order" type="number" defaultValue={project?.sort_order??99}/><label className="flex items-center gap-2 text-sm"><input name="published" type="checkbox" defaultChecked={project?.published??true}/> Published</label><div className="flex gap-2 sm:col-span-2"><Button type="submit"><Save/>Save project</Button>{onDelete&&<Button type="button" variant="destructive" onClick={onDelete}><Trash2/>Delete</Button>}</div></form>}
function SimpleTable({rows,columns,table,reload}:{rows:Array<Record<string,unknown>>;columns:string[];table:"skills"|"experiences";reload:()=>Promise<void>}){return <div className="space-y-3">{rows.map(row=><form key={String(row.id)} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const payload=Object.fromEntries(columns.map(c=>[c,c==="level"||c==="sort_order"?Number(f.get(c)):String(f.get(c))]));await supabase.from(table).update(payload).eq("id",String(row.id));await reload()}} className="grid gap-3 border border-border bg-surface p-4 md:grid-cols-6">{columns.map(c=><Input key={c} name={c} defaultValue={String(row[c]??"")} className="md:col-span-1"/>)}<Button type="submit" size="icon" aria-label="Save"><Save/></Button></form>)}</div>}